apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment
    app: demo-vote-app
spec:
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: demo-vote-app
    spec:
      containers:
        - name: result
          image: ashiqummathoor/resultnew
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      name: result-pod
      app: demo-vote-app