apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-servie
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    name: vote-pod
    app: demo-vote-app