apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
    app: demo-vote-app
spec:
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-vote-app
    spec:
      containers:
        - name: worker
          image: ashiqummathoor/workernew
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: demo-vote-app